language: node_js
services:
  - docker

script:
  - yarn test
  - docker build --build-arg GITHUB_DEPLOY_KEY="$DEPLOY_KEY" -t $DOCKER_REGISTRY/schnitzelcountdown-update-server:latest .

after_success:
  - >
    if [ "$TRAVIS_BRANCH" == "master" ] && [ "$TRAVIS_PULL_REQUEST" == "false" ]; then
      docker login -u="$DOCKER_USER" -p="$DOCKER_PASS" $DOCKER_REGISTRY
      docker push $DOCKER_REGISTRY/schnitzelcountdown-update-server:latest
    fi
